<template>
  <div class="relative min-h-screen flex flex-col items-center justify-center bg-gray-100 p-4 overflow-hidden">
    
    <!-- Main Login Card -->
    <div class="w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-6 z-10">
      <div class="flex justify-center mb-3">
          <img src="/pwa-512x512.png" alt="Logo" class="h-24 w-24">
        </div>
      <div class="text-center">
        <h1 class="text-3xl font-bold text-gray-800">{{ companyName || 'Sign In' }}</h1>
        <p class="text-gray-500 mt-2">Access your backoffice dashboard</p>
      </div>
      
      <form @submit.prevent="handleLogin" class="space-y-6">
        <div>
          <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
          <input
            v-model="username"
            type="text"
            id="username"
            class="mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="e.g., ishani"
          />
        </div>
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input
            v-model="password"
            type="password"
            id="password"
            class="mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="••••••••"
          />
        </div>

        <div v-if="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-md text-sm">
          <p>{{ errorMessage }}</p>
        </div>

        <!-- 01. FORGOT PASSWORD MESSAGE AREA (New) -->
        <div v-if="showForgotPasswordMessage" class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded-md text-sm">
          <p>Please contact your system administrator to reset your password.</p>
        </div>

        <div>
          <button
            type="submit"
            :disabled="isLoading"
            class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-400 disabled:cursor-not-allowed"
          >
            <span v-if="isLoading">Signing In...</span>
            <span v-else>Sign In</span>
          </button>
        </div>
      </form>

      <!-- Links Section (New) -->
      <div class="text-sm text-center flex justify-between items-center">
        <a @click.prevent="showForgotPasswordMessage = !showForgotPasswordMessage" href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
          Forgot Password?
        </a>
        <a @click.prevent="showTermsModal = true" href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
          Terms & Conditions
        </a>
      </div>
    </div>

    <!-- 02. FOOTER (New) -->
    <footer class="absolute bottom-4 text-center text-gray-500 text-sm z-10">
      <p>&copy; 2025 Caspersoft. All rights reserved.</p>
    </footer>

    <!-- 03. TERMS AND CONDITIONS MODAL (New) -->
    <div v-if="showTermsModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col">
        <div class="p-6 border-b">
          <h2 class="text-2xl font-bold text-gray-800">Terms and Conditions</h2>
        </div>
        <div class="p-6 overflow-y-auto space-y-4 text-gray-600">
          <p><strong>Last Updated:</strong> 21 July 2025</p>
          <p>Welcome to the backoffice system. By accessing or using this platform, you agree to be bound by these terms. This system functions as an Enterprise Resource Planning (ERP) tool for our Point of Sale (POS) network.</p>
          <h3 class="font-semibold text-gray-700">1. System Usage</h3>
          <p>This system is for authorized business purposes only, including but not limited to dashboard analytics, stock management, order processing, and reporting. Unauthorized access or use is strictly prohibited.</p>
          <h3 class="font-semibold text-gray-700">2. User Responsibilities</h3>
          <p>You are responsible for maintaining the confidentiality of your login credentials. All activities that occur under your account are your responsibility. You agree to input accurate and truthful data into the system.</p>
          <h3 class="font-semibold text-gray-700">3. Data and Intellectual Property</h3>
          <p>All data entered into and generated by this system is the property of the company. You may not copy, distribute, or disclose any part of the system or its data without prior written authorization.</p>
           <h3 class="font-semibold text-gray-700">4. Limitation of Liability</h3>
          <p>The system is provided "as-is". While we strive for accuracy and uptime, we are not liable for any business losses, data corruption, or other damages resulting from the use of or inability to use this platform.</p>
        </div>
        <div class="p-4 bg-gray-50 border-t text-right">
          <button @click="showTermsModal = false" class="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700">
            Close
          </button>
        </div>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useAuthStore } from '@/stores/auth';
import { storeToRefs } from 'pinia';

const authStore = useAuthStore();
const { companyName } = storeToRefs(authStore);

const username = ref('');
const password = ref('');
const isLoading = ref(false);
const errorMessage = ref('');

// --- NEW STATE VARIABLES ---
const showForgotPasswordMessage = ref(false); // For the forgot password message
const showTermsModal = ref(false); // For the terms modal

onMounted(() => {
  authStore.fetchCompany();
});

const handleLogin = async () => {
  errorMessage.value = '';
  showForgotPasswordMessage.value = false; // Hide message on new login attempt
  isLoading.value = true;
  try {
    await authStore.login(username.value, password.value);
  } catch (error) {
    errorMessage.value = error.message || 'An unexpected error occurred.';
  } finally {
    isLoading.value = false;
  }
};
</script>
